repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--config, .flake8]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
